# Generated by Django 5.1 on 2024-08-19 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_add_slug_to_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="first_Name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="last_Name",
            new_name="last_name",
        ),
    ]
