# Generated by Django 5.1 on 2024-08-19 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_rename_first_name_customer_first_name_and_more"),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection1')
                          """, """
            DELETE FROM store_collection
            WHERE title = 'collection1'
                          
                          """)
    ]
